using System.Globalization;

namespace WinMonitor.Localization;

/// <summary>
/// Minimal string-table localization. No resx, no satellite assemblies — two inline
/// dictionaries keep the footprint tiny. Unknown keys fall back to English, then the key
/// itself, so a missing translation can never crash or blank the UI.
/// </summary>
public static class Loc
{
    public const string English = "en";
    public const string ChineseTraditional = "zh-TW";

    public static string Current { get; private set; } = English;

    public static event Action? LanguageChanged;

    /// <summary>language: "auto" | "en" | "zh-TW"</summary>
    public static void Initialize(string language)
    {
        string resolved = language;
        if (language is "auto" or "" or null)
        {
            var ui = CultureInfo.CurrentUICulture.Name;
            resolved = ui.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? ChineseTraditional : English;
        }
        Current = resolved == ChineseTraditional ? ChineseTraditional : English;
        LanguageChanged?.Invoke();
    }

    public static string T(string key)
    {
        if (Current == ChineseTraditional && ZhTw.TryGetValue(key, out var zh)) return zh;
        if (En.TryGetValue(key, out var en)) return en;
        return key;
    }

    public static string F(string key, params object[] args) => string.Format(CultureInfo.CurrentCulture, T(key), args);

    private static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        // App
        ["app.name"] = "WinMonitor",
        ["app.already_running"] = "WinMonitor is already running. The existing window has been shown.",

        // Categories
        ["cat.cpu"] = "CPU",
        ["cat.gpu"] = "GPU",
        ["cat.storage"] = "Storage",
        ["cat.memory"] = "Memory",
        ["cat.battery"] = "Battery",
        ["cat.fan"] = "Fans",
        ["cat.motherboard"] = "Motherboard",
        ["cat.other"] = "Other",

        // Main window
        ["main.col.sensor"] = "Sensor",
        ["main.col.value"] = "Current",
        ["main.col.min"] = "Min",
        ["main.col.max"] = "Max",
        ["main.col.avg"] = "Avg",
        ["main.col.extra"] = "Info",
        ["main.reset_peaks"] = "Reset peaks",
        ["main.export_csv"] = "Export time-series CSV",
        ["main.settings"] = "Settings",
        ["main.compact"] = "Compact mode",
        ["main.full"] = "Full window",
        ["main.chart"] = "Chart",
        ["main.chart_minutes"] = "Window (min)",
        ["chart.temperature"] = "Temperature",
        ["chart.power"] = "Power",
        ["chart.fan"] = "Fan speed",
        ["chart.percent"] = "Percentage",
        ["chart.frequency"] = "Frequency",
        ["chart.voltage"] = "Voltage",
        ["chart.data"] = "Data",
        ["main.profile"] = "Profile",
        ["main.poll"] = "Polling",
        ["main.poll.1s"] = "1 s (precise)",
        ["main.poll.2s"] = "2 s (default)",
        ["main.poll.5s"] = "5 s (eco)",
        ["main.not_elevated"] = "Running without administrator rights — CPU/SSD/fan sensors may be unavailable. Restart as administrator for full data.",
        ["main.cpu_unavailable"] = "CPU temperature, power, and frequency are unavailable. Install or update PawnIO, then restart WinMonitor.",
        ["main.cpu_unavailable_old_pawnio"] = "PawnIO {0} is too old for this sensor backend. Update to PawnIO 2.2.0 or newer, then restart WinMonitor.",
        ["main.pawnio_hint"] = "Tip: installing the signed PawnIO driver improves sensor access on Windows 11 (see Settings → General).",
        ["main.exit"] = "Exit",
        ["main.file"] = "File",
        ["main.view"] = "View",
        ["main.help"] = "Help",
        ["main.about"] = "About",
        ["main.export_done"] = "Exported to {0}",
        ["main.export_truncated"] = "Note: the session history reached its size cap, so the newest samples are missing from this file.",
        ["main.export_busy"] = "A CSV export is still running. Exiting now will leave a truncated file.\r\n\r\nExit anyway?",
        ["mem.no_sensor"] = "Most consumer memory modules have no dedicated temperature sensor.",
        ["main.no_fans"] = "No fan sensors detected. Many laptops (including LG gram) hide fan control behind a proprietary EC that exposes no standard interface.",
        ["main.confirm_close.title"] = "Close WinMonitor",
        ["main.confirm_close.text"] = "Minimize to tray instead of exiting?",
        ["main.confirm_close.minimize"] = "Minimize to tray",
        ["main.confirm_close.exit"] = "Exit program",
        ["main.dont_ask_again"] = "Don't ask again",

        // Tray
        ["tray.open"] = "Open WinMonitor",
        ["tray.settings"] = "Settings…",
        ["tray.compact"] = "Compact mode",
        ["tray.reset_peaks"] = "Reset peaks",
        ["tray.open_logs"] = "Open log folder",
        ["tray.task_manager"] = "Task Manager",
        ["tray.exit"] = "Exit",
        ["tray.min"] = "min",
        ["tray.max"] = "max",

        // Alerts
        ["alert.title"] = "Sensor alert",
        ["alert.body"] = "{0} reached {1} (threshold {2})",

        // Settings — general
        ["set.title"] = "Settings",
        ["set.tab.general"] = "General",
        ["set.tab.tray"] = "Tray icons",
        ["set.tab.sensors"] = "Sensors",
        ["set.tab.alerts"] = "Alerts",
        ["set.tab.profiles"] = "Profiles",
        ["set.tab.diagnostics"] = "Diagnostics",
        ["set.language"] = "Language",
        ["set.language.auto"] = "Auto (system)",
        ["set.units"] = "Temperature unit",
        ["set.poll_interval"] = "Polling interval",
        ["set.autostart"] = "Start with Windows",
        ["set.autostart_delay"] = "Startup delay (seconds)",
        ["set.autostart_hint"] = "Elevated: registered as a Task Scheduler task (no UAC prompt). Portable/non-admin: registered under HKCU Run.",
        ["set.start_minimized"] = "Start minimized (tray only)",
        ["set.close_to_tray"] = "Close button minimizes to tray",
        ["set.confirm_on_close"] = "Ask before closing",
        ["set.logging"] = "Background logging (CSV)",
        ["set.logging_interval"] = "Log every (seconds)",
        ["set.logging_retention"] = "Keep logs (days)",
        ["set.pawnio.installed"] = "PawnIO driver: detected",
        ["set.pawnio.missing"] = "PawnIO driver: not installed (optional; https://pawnio.eu)",
        ["set.restore_defaults"] = "Restore defaults",
        ["set.restore_defaults.confirm"] = "Reset ALL settings, profiles and sensor customizations to defaults?",

        // Settings — tray
        ["set.tray.list"] = "Tray icons (top = leftmost)",
        ["set.tray.add"] = "Add icon",
        ["set.tray.remove"] = "Remove icon",
        ["set.tray.up"] = "Move up",
        ["set.tray.down"] = "Move down",
        ["set.tray.sensors"] = "Sensors shown by this icon (2+ = carousel)",
        ["set.tray.rotate"] = "Carousel interval (seconds)",
        ["set.tray.style"] = "Style",
        ["set.tray.style.text"] = "Colored text",
        ["set.tray.style.badge"] = "Text on colored badge",
        ["set.tray.show_unit"] = "Show unit",
        ["set.tray.bold"] = "Bold",
        ["set.tray.color_override"] = "Fixed color (instead of threshold colors)",
        ["set.tray.pick_color"] = "Pick…",
        ["set.tray.threshold_colors"] = "Use threshold colors",

        // Settings — sensors
        ["set.sens.col.hardware"] = "Hardware",
        ["set.sens.col.sensor"] = "Sensor",
        ["set.sens.col.rename"] = "Custom name",
        ["set.sens.col.hidden"] = "Hidden",
        ["set.sens.col.yellow"] = "Yellow ≥",
        ["set.sens.col.red"] = "Red ≥",
        ["set.sens.suggest"] = "Suggest thresholds",
        ["set.sens.hint"] = "Leave name empty to keep the original. Thresholds are in the sensor's own unit (°C, RPM, %).",

        // Settings — alerts
        ["set.alert.enable"] = "Alert",
        ["set.alert.sustain"] = "Sustain (s)",
        ["set.alert.sound"] = "Sound",
        ["set.alert.sound.system"] = "System sound",
        ["set.alert.sound.custom"] = "Custom WAV…",
        ["set.alert.test"] = "Test",
        ["set.alert.hint"] = "A toast fires only after the value stays above the red threshold for the sustain time (filters momentary spikes). It re-arms when the value falls below yellow.",

        // Settings — profiles
        ["set.prof.active"] = "Active profile",
        ["set.prof.add"] = "New",
        ["set.prof.clone"] = "Clone",
        ["set.prof.rename"] = "Rename",
        ["set.prof.delete"] = "Delete",
        ["set.prof.name_prompt"] = "Profile name:",
        ["set.prof.delete_confirm"] = "Delete profile \"{0}\"?",
        ["set.prof.hint"] = "Each profile has its own tray icons and threshold overrides (e.g. Daily / Gaming / Silent).",

        // Settings — diagnostics
        ["set.diag.hint"] = "Live polling health and support details. This page refreshes once per second and does not change settings.",
        ["set.diag.copy"] = "Copy diagnostics",
        ["set.diag.status"] = "Service status",
        ["set.diag.running"] = "Running",
        ["set.diag.stopped"] = "Stopped",
        ["set.diag.successful_polls"] = "Successful polls",
        ["set.diag.failed_polls"] = "Failed polls",
        ["set.diag.node_failures"] = "Node update failures",
        ["set.diag.last_poll"] = "Last poll duration",
        ["set.diag.last_snapshot"] = "Values in last snapshot",
        ["set.diag.descriptors"] = "Detected descriptors",
        ["set.diag.last_success"] = "Last successful poll",
        ["set.diag.last_failure"] = "Last failure",
        ["set.diag.failure_detail"] = "Failure detail",
        ["set.diag.elevation"] = "Administrator access",
        ["set.diag.cpu_telemetry"] = "CPU telemetry",
        ["set.diag.pawnio"] = "PawnIO",
        ["set.diag.available"] = "Available",
        ["set.diag.unavailable"] = "Unavailable",
        ["set.diag.never"] = "Never",
        ["set.diag.none"] = "None",
        ["set.diag.milliseconds"] = "ms",
        ["set.diag.history_size"] = "Session history spool",
        ["set.diag.history_truncated"] = "(cap reached — newest samples are not exported)",
        ["set.diag.open_log"] = "Open diagnostic log",
        ["set.diag.no_log"] = "No diagnostic log has been written yet.",
        ["set.diag.ec_explorer"] = "EC register explorer…",

        // Settings tooltips
        ["tip.tabs"] = "Choose a category of settings. Hover an individual option for a detailed explanation.",
        ["tip.tab.general"] = "Language, appearance, polling, startup, logging, and monitoring behavior.",
        ["tip.tab.tray"] = "Configure the notification-area icons and the readings each icon shows.",
        ["tip.tab.sensors"] = "Rename, hide, and set visual warning thresholds for detected sensors.",
        ["tip.tab.alerts"] = "Choose which sensors send notifications and how alerts behave.",
        ["tip.tab.profiles"] = "Create named sets of tray icons and threshold overrides.",
        ["tip.tab.diagnostics"] = "Inspect live sensor-polling health and copy details for troubleshooting.",
        ["tip.diagnostics.hint"] = "Shows the latest polling result, failures, backend availability, and timing. No settings are changed here.",
        ["tip.diagnostics.copy"] = "Copies the current diagnostic report to the clipboard for a support request or issue report.",
        ["tip.diagnostics.open_log"] = "Opens the rolling diagnostic log. Unlike this page it survives sleep, crashes and restarts, so it is the place to look for a fault that already happened.",
        ["tip.diagnostics.ec_explorer"] = "Opens the Embedded Controller register explorer used to discover fan registers on laptop models that have no built-in mapping.",
        ["tip.common.apply"] = "Save changes made in this dialog and keep the Settings window open.",
        ["tip.common.cancel"] = "Discard changes made since the last Apply, or since this window was opened.",
        ["tip.common.ok"] = "Save changes and close the Settings window.",

        ["tip.general.language"] = "Changes the display language. Auto follows the Windows display language after settings are applied.",
        ["tip.general.theme"] = "Chooses light, dark, or automatic appearance. Auto follows the Windows app theme.",
        ["tip.general.units"] = "Controls temperature display only. Sensor data remains stored in Celsius.",
        ["tip.general.poll_interval"] = "How often hardware is read. Shorter intervals react faster but use more CPU and battery.",
        ["tip.general.battery_adaptive"] = "When on battery, reduces sensor work where possible to extend battery life. Readings can update less often.",
        ["tip.general.autostart"] = "Starts WinMonitor when you sign in. Elevated installs use Task Scheduler; portable or standard-user installs use HKCU Run.",
        ["tip.general.autostart_delay"] = "Waits after sign-in before starting. Useful while Windows and hardware drivers are still loading.",
        ["tip.general.start_minimized"] = "Starts without the main window. WinMonitor remains available through its notification-area icon.",
        ["tip.general.close_to_tray"] = "Makes the window Close button hide WinMonitor instead of stopping sensor monitoring.",
        ["tip.general.confirm_on_close"] = "When Close-to-tray is enabled, asks whether to hide to the tray or exit the program.",
        ["tip.general.hotkey"] = "Lets Ctrl+Alt+M toggle Compact view while WinMonitor is running.",
        ["tip.general.show_cores"] = "Adds individual CPU-core temperature readings to the main sensor list. When off, only package or aggregate CPU temperatures remain.",
        ["tip.general.flag_static"] = "Marks ACPI or other temperature zones that do not change, so they are not mistaken for live readings.",
        ["tip.general.throttle"] = "Shows a CPU thermal-throttling status sensor when the hardware backend supports it.",
        ["tip.general.throttle_toast"] = "Shows a notification when thermal throttling begins. Available only when throttling detection is enabled.",
        ["tip.general.auto_reset_daily"] = "Resets session minimum, maximum, and average values at the selected time every day.",
        ["tip.general.auto_reset_time"] = "The local time used for the automatic daily reset.",
        ["tip.general.reset_on_resume"] = "Clears session peaks after Windows resumes because readings from before sleep may not be comparable.",
        ["tip.general.ec_throttle"] = "Reads configured EC sensors every N normal polling cycles. Higher values reduce EC access but update fan readings less often.",
        ["tip.general.logging"] = "Writes snapshots to daily CSV files in the configured log folder. This enables background disk activity.",
        ["tip.general.logging_interval"] = "Number of seconds between CSV rows. This is independent of the live polling interval.",
        ["tip.general.logging_retention"] = "Deletes older CSV log files after this many days.",
        ["tip.general.pawnio"] = "Shows whether optional signed PawnIO access is available. It can improve hardware data availability on Windows.",
        ["tip.general.restore_defaults"] = "Replaces all settings, profiles, and sensor customizations with defaults after confirmation.",

        ["tip.tray.list"] = "Each row is one independent notification-area icon. Earlier rows appear farther left in the notification area.",
        ["tip.tray.add"] = "Adds an empty tray-icon entry. Choose its sensors from the list on the right.",
        ["tip.tray.remove"] = "Deletes the selected tray-icon entry. At least one entry is kept.",
        ["tip.tray.up"] = "Moves the selected tray icon one position left in the notification area.",
        ["tip.tray.down"] = "Moves the selected tray icon one position right in the notification area.",
        ["tip.tray.split"] = "Replaces a carousel entry with one icon per chosen sensor while preserving its style settings.",
        ["tip.tray.sensors"] = "Choose readings for the selected icon. One reading stays visible; two or more readings rotate.",
        ["tip.tray.rotate"] = "How long a carousel shows one sensor before advancing. It affects entries with two or more sensors only.",
        ["tip.tray.style"] = "Chooses colored text or text on a colored badge for the selected tray icon.",
        ["tip.tray.show_unit"] = "Adds a unit such as \u00B0C, W, or % to icon text. This can leave less room for the number.",
        ["tip.tray.bold"] = "Draws the tray-icon text in bold. It can improve legibility but leaves less room for numbers.",
        ["tip.tray.sparkline"] = "Draws a miniature recent-trend graph when space and sensor history are available.",
        ["tip.tray.threshold_colors"] = "Colors icon text from the sensor's green, yellow, or red threshold state.",
        ["tip.tray.fixed_color"] = "Uses the selected fixed color and ignores severity-based threshold colors.",
        ["tip.tray.pick_color"] = "Opens a color picker for fixed-color mode. Picking a color enables fixed-color mode.",

        ["tip.sens.filter"] = "Limits the grid to sensor or hardware names that contain the typed text.",
        ["tip.sens.grid"] = "Edit each sensor's name, visibility, and visual thresholds. Hover a column for its specific behavior.",
        ["tip.sens.hardware"] = "Identifies the physical device that supplies this reading. It cannot be edited here.",
        ["tip.sens.sensor"] = "The original sensor name reported by the hardware backend. It cannot be edited here.",
        ["tip.sens.rename"] = "Optional replacement name shown throughout WinMonitor. Clear it to use the original hardware name.",
        ["tip.sens.hidden"] = "Removes the sensor from main lists and all tray entries. It does not stop background hardware polling.",
        ["tip.sens.yellow"] = "Warning-color threshold in the sensor's own unit. Clear the cell to inherit the global or suggested value.",
        ["tip.sens.red"] = "Critical-color threshold in the sensor's own unit. Clear the cell to inherit the global or suggested value.",
        ["tip.sens.suggest"] = "Writes suggested yellow and red thresholds to selected rows while preserving alert settings.",
        ["tip.sens.restore_all"] = "Resets yellow and red thresholds for every profile to suggested defaults while keeping names, hidden flags, and alerts.",

        ["tip.alert.filter"] = "Limits the grid to sensor or hardware names that contain the typed text.",
        ["tip.alert.grid"] = "Enable notifications for supported sensors, choose the delay before firing, and decide whether an alert plays sound.",
        ["tip.alert.sensor"] = "The monitored sensor. Only temperatures, fan speeds, and power readings can raise alerts.",
        ["tip.alert.enable"] = "Enables a notification when the value remains above its red threshold for the sustain time.",
        ["tip.alert.sustain"] = "Number of continuous seconds above the red threshold before an alert fires. Allowed range: 1 to 3600.",
        ["tip.alert.sound"] = "Lets this sensor's alert play the configured system sound or custom WAV file.",
        ["tip.alert.sound_mode"] = "Choose a system alert sound or a custom WAV file for testing and for applying to all enabled alerts.",
        ["tip.alert.sound_path"] = "Path to the custom WAV file. It is saved only when Apply sound to all alerts is used.",
        ["tip.alert.browse"] = "Select a WAV file for the custom alert sound.",
        ["tip.alert.test"] = "Plays the currently selected system or custom sound without saving changes.",
        ["tip.alert.apply_sound_all"] = "Saves the current sound choice to every enabled alert in the active profile, even when the grid is filtered.",

        ["tip.profiles.active"] = "Selects the profile whose tray icons and threshold overrides are used after settings are applied.",
        ["tip.profiles.list"] = "Select a profile to clone, rename, or delete. Profiles keep separate tray-icon and threshold settings.",
        ["tip.profiles.new"] = "Creates a new profile with default tray and threshold settings.",
        ["tip.profiles.clone"] = "Copies the selected profile, including its tray icons and threshold overrides, into a new profile.",
        ["tip.profiles.rename"] = "Changes the selected profile's name without changing its settings.",
        ["tip.profiles.delete"] = "Deletes the selected profile after confirmation. The final remaining profile cannot be deleted.",
        ["tip.profiles.name"] = "Enter a non-empty profile name that is different from every existing profile name.",

        ["set.alert.browse"] = "…",

        // Battery extra
        ["bat.charge"] = "Charge",
        ["bat.health"] = "Health",
        ["bat.rate"] = "Rate",
        ["bat.remaining_capacity"] = "Remaining capacity",

        // Storage extra
        ["ssd.health"] = "Health",
        ["ssd.written"] = "Written",

        // Common
        ["common.ok"] = "OK",
        ["common.cancel"] = "Cancel",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.close"] = "Close",
        ["common.celsius"] = "Celsius (°C)",
        ["common.fahrenheit"] = "Fahrenheit (°F)",
        ["common.none"] = "(none)",
        ["common.error"] = "Error",
        ["common.apply"] = "Apply",

        // Module-contributed keys
        ["sensor.acpi_zone"] = "ACPI Thermal Zone",
        ["startup.register_failed"] = "Autostart registration failed: {0}",
        ["startup.task_description"] = "Starts WinMonitor when you sign in to Windows.",
        ["main.use_fahrenheit"] = "Fahrenheit (°F)",
        ["main.show_chart"] = "Show chart",
        ["main.about_text"] = "Lightweight hardware monitor for Windows.\n\nCopyright (c) 2026 Michael Lin.\nWinMonitor source code is licensed under the MIT License. Third-party license texts are included with the application.\n\nSensor data powered by LibreHardwareMonitor (LibreHardwareMonitorLib, MPL-2.0).\nhttps://github.com/LibreHardwareMonitor/LibreHardwareMonitor",
        ["main.status.elevated"] = "Administrator",
        ["main.status.not_elevated"] = "Standard user",
        ["main.status.cpu_unavailable"] = "CPU telemetry unavailable",
        ["main.status.pawnio"] = "PawnIO detected",
        ["file.csv_filter"] = "CSV files (*.csv)|*.csv|All files (*.*)|*.*",
        ["set.tray.icon_label"] = "Icon {0}: {1}",
        ["set.tray.auto"] = "(auto)",
        ["set.alert.apply_sound_all"] = "Apply sound to all alerts",
        ["set.tray.split"] = "One icon per sensor",
        ["set.tray.independent_hint"] = "Each entry in the left list is its own independent tray icon. Checking multiple sensors in ONE entry makes that icon cycle through them.",
        ["set.sens.restore_all"] = "Restore suggested thresholds",
        ["set.sens.restore_all.confirm"] = "Reset yellow/red thresholds of ALL sensors (all profiles) to the suggested defaults? Renames, hidden flags and alert settings are kept.",

        // Embedded Controller (LG fan reading)
        ["ec.title"] = "Embedded Controller Explorer",
        ["ec.hint"] = "Three ways to find the fan register without guessing. Correlation (top right): just use the laptop normally for ~1 minute — registers that track CPU temp/load rise to the top; double-click one to add it. Find value: type an RPM you see in another tool to locate which register holds it. Capture A/B: snapshot idle, then loaded, to see only the biggest movers.",
        ["ec.correlation"] = "Likely fan / thermal",
        ["ec.likely_header"] = "Ranked by how closely each register tracks CPU temp / load. Double-click to add.",
        ["ec.collecting"] = "Collecting samples… {0}/{1}",
        ["ec.no_candidates"] = "No strong candidates yet — keep using the laptop.",
        ["ec.target_temp"] = "temp",
        ["ec.target_load"] = "load",
        ["ec.find_value"] = "Find value (RPM from another tool)",
        ["ec.compare"] = "Idle → load diff (biggest movers)",
        ["ec.compare_hint"] = "Capture A while idle, then Capture B under load.",
        ["ec.compare_none"] = "No register moved by 3 or more between A and B.",
        ["ec.capture_a"] = "Capture A (idle)",
        ["ec.capture_b"] = "Capture B (load)",
        ["ec.capture_a_done"] = "A captured ✓",
        ["ec.capture_b_done"] = "B captured ✓",
        ["ec.defined"] = "Monitored EC sensors",
        ["ec.add"] = "Add selected as sensor…",
        ["ec.remove"] = "Remove",
        ["ec.reset_minmax"] = "Reset min/max",
        ["ec.select_prompt"] = "Select a register to see details.",
        ["ec.unavailable"] = "EC not available. Run WinMonitor as administrator with PawnIO installed.",
        ["ec.likely_fan"] = "This register changes a lot — a likely fan / thermal candidate.",
        ["ec.add_title"] = "Add EC sensor (register {0})",
        ["ec.default_name"] = "CPU Fan",
        ["ec.field_name"] = "Name",
        ["ec.field_kind"] = "Interpretation",
        ["ec.field_quantity"] = "Quantity",
        ["ec.field_scale"] = "Scale (×)",
        ["ec.field_divisor"] = "Divisor",
        ["ec.big_endian"] = "Big-endian word (high byte first)",
        ["ec.preview"] = "Preview",
        ["ec.status.available"] = "EC: available (PawnIO)",
        ["ec.status.pawnio_missing"] = "EC: PawnIO not installed",
        ["ec.status.not_elevated"] = "EC: needs administrator",
        ["ec.status.module_missing"] = "EC: module file missing",
        ["ec.status.failed"] = "EC: initialization failed",
        ["ec.enable"] = "Enable Embedded Controller monitoring (LG fan support)",

        // Round-3 optimizations
        ["main.show_cores"] = "Show per-core temperatures",
        ["main.fixed_value"] = "(fixed)",
        ["set.battery_adaptive"] = "Reduce polling on battery",
        ["set.show_cores"] = "Show per-core CPU temperatures",
        ["set.flag_static"] = "Mark unchanging temperature zones as (fixed)",
        ["set.ec_throttle"] = "Read EC every N polls",
        ["set.tray.sparkline"] = "Show mini trend graph",

        // Round-4 batch
        ["throttle.sensor"] = "Thermal throttling",
        ["throttle.normal"] = "Normal",
        ["throttle.active"] = "Throttling",
        ["boolean.true"] = "True",
        ["boolean.false"] = "False",
        ["chart.boolean"] = "Status",
        ["throttle.toast_title"] = "CPU thermal throttling",
        ["throttle.toast_body"] = "The CPU reached its thermal limit and is being slowed down.",
        ["main.ctx.tray"] = "Show in tray",
        ["main.ctx.pin"] = "Pin to favorites",
        ["main.ctx.hide"] = "Hide sensor",
        ["main.group.favorites"] = "Favorites",
        ["main.rescan"] = "Rescan hardware",
        ["main.statuscard.copy"] = "Copy status card",
        ["main.statuscard.save"] = "Save status card…",
        ["set.filter"] = "Filter sensors…",
        ["set.theme"] = "Theme",
        ["set.theme.auto"] = "Auto",
        ["set.theme.light"] = "Light",
        ["set.theme.dark"] = "Dark",
        ["set.hotkey"] = "Global hotkey toggles compact view (Ctrl+Alt+M)",
        ["set.throttle"] = "Detect CPU thermal throttling",
        ["set.throttle_toast"] = "Notify when throttling starts",
        ["set.autoreset_daily"] = "Reset peaks daily at",
        ["set.autoreset_resume"] = "Reset peaks on wake from sleep",
    };

    private static readonly Dictionary<string, string> ZhTw = new(StringComparer.Ordinal)
    {
        // App
        ["app.name"] = "WinMonitor",
        ["app.already_running"] = "WinMonitor 已在執行中，已為你開啟現有視窗。",

        // Categories
        ["cat.cpu"] = "處理器",
        ["cat.gpu"] = "顯示晶片",
        ["cat.storage"] = "儲存裝置",
        ["cat.memory"] = "記憶體",
        ["cat.battery"] = "電池",
        ["cat.fan"] = "風扇",
        ["cat.motherboard"] = "主機板",
        ["cat.other"] = "其他",

        // Main window
        ["main.col.sensor"] = "感測器",
        ["main.col.value"] = "目前",
        ["main.col.min"] = "最低",
        ["main.col.max"] = "最高",
        ["main.col.avg"] = "平均",
        ["main.col.extra"] = "資訊",
        ["main.reset_peaks"] = "重設峰值",
        ["main.export_csv"] = "匯出時間序列 CSV",
        ["main.settings"] = "設定",
        ["main.compact"] = "迷你模式",
        ["main.full"] = "完整視窗",
        ["main.chart"] = "圖表",
        ["main.chart_minutes"] = "時間範圍（分鐘）",
        ["chart.temperature"] = "溫度",
        ["chart.power"] = "功率",
        ["chart.fan"] = "風扇轉速",
        ["chart.percent"] = "百分比",
        ["chart.frequency"] = "頻率",
        ["chart.voltage"] = "電壓",
        ["chart.data"] = "資料量",
        ["main.profile"] = "設定檔",
        ["main.poll"] = "輪詢間隔",
        ["main.poll.1s"] = "1 秒（高精度）",
        ["main.poll.2s"] = "2 秒（預設）",
        ["main.poll.5s"] = "5 秒（省資源）",
        ["main.not_elevated"] = "目前以一般權限執行——CPU／SSD／風扇感測器可能無法讀取。請以系統管理員身分重新啟動以取得完整資料。",
        ["main.cpu_unavailable"] = "CPU 溫度、功耗與頻率目前無法讀取。請安裝或更新 PawnIO，然後重新啟動 WinMonitor。",
        ["main.cpu_unavailable_old_pawnio"] = "PawnIO {0} 版本過舊，無法供目前的感測後端使用。請更新至 PawnIO 2.2.0 以上，然後重新啟動 WinMonitor。",
        ["main.pawnio_hint"] = "提示：安裝已簽章的 PawnIO 驅動可改善 Windows 11 上的感測器存取（見 設定 → 一般）。",
        ["main.exit"] = "結束",
        ["main.file"] = "檔案",
        ["main.view"] = "檢視",
        ["main.help"] = "說明",
        ["main.about"] = "關於",
        ["main.export_done"] = "已匯出至 {0}",
        ["main.export_truncated"] = "注意：工作階段歷史已達容量上限，最新的取樣未包含在此檔案中。",
        ["main.export_busy"] = "CSV 匯出仍在進行中。現在結束會留下不完整的檔案。\r\n\r\n仍要結束嗎？",
        ["mem.no_sensor"] = "多數消費級記憶體模組沒有獨立的溫度感測器。",
        ["main.no_fans"] = "未偵測到風扇感測器。許多筆電（包含 LG gram）的風扇由專屬 EC 控制，未提供標準讀取介面。",
        ["main.confirm_close.title"] = "關閉 WinMonitor",
        ["main.confirm_close.text"] = "要縮小到系統匣而不是結束程式嗎？",
        ["main.confirm_close.minimize"] = "縮小到系統匣",
        ["main.confirm_close.exit"] = "結束程式",
        ["main.dont_ask_again"] = "不要再詢問",

        // Tray
        ["tray.open"] = "開啟 WinMonitor",
        ["tray.settings"] = "設定…",
        ["tray.compact"] = "迷你模式",
        ["tray.reset_peaks"] = "重設峰值",
        ["tray.open_logs"] = "開啟記錄資料夾",
        ["tray.task_manager"] = "工作管理員",
        ["tray.exit"] = "結束",
        ["tray.min"] = "低",
        ["tray.max"] = "高",

        // Alerts
        ["alert.title"] = "感測器警示",
        ["alert.body"] = "{0} 已達 {1}（門檻 {2}）",

        // Settings — general
        ["set.title"] = "設定",
        ["set.tab.general"] = "一般",
        ["set.tab.tray"] = "系統匣圖示",
        ["set.tab.sensors"] = "感測器",
        ["set.tab.alerts"] = "警示",
        ["set.tab.profiles"] = "設定檔",
        ["set.tab.diagnostics"] = "診斷",
        ["set.language"] = "語言",
        ["set.language.auto"] = "自動（跟隨系統）",
        ["set.units"] = "溫度單位",
        ["set.poll_interval"] = "輪詢間隔",
        ["set.autostart"] = "開機時自動啟動",
        ["set.autostart_delay"] = "啟動延遲（秒）",
        ["set.autostart_hint"] = "系統管理員模式：註冊為排程工作（不會跳 UAC）。免安裝／一般權限：寫入 HKCU Run 登錄機碼。",
        ["set.start_minimized"] = "啟動時最小化（僅系統匣）",
        ["set.close_to_tray"] = "按關閉鈕時縮小到系統匣",
        ["set.confirm_on_close"] = "關閉前詢問",
        ["set.logging"] = "背景記錄（CSV）",
        ["set.logging_interval"] = "記錄間隔（秒）",
        ["set.logging_retention"] = "保留天數",
        ["set.pawnio.installed"] = "PawnIO 驅動：已安裝",
        ["set.pawnio.missing"] = "PawnIO 驅動：未安裝（選用；https://pawnio.eu）",
        ["set.restore_defaults"] = "還原預設值",
        ["set.restore_defaults.confirm"] = "確定要將所有設定、設定檔與感測器自訂全部還原為預設值？",

        // Settings — tray
        ["set.tray.list"] = "系統匣圖示（上方 = 最左邊）",
        ["set.tray.add"] = "新增圖示",
        ["set.tray.remove"] = "移除圖示",
        ["set.tray.up"] = "上移",
        ["set.tray.down"] = "下移",
        ["set.tray.sensors"] = "此圖示顯示的感測器（2 個以上 = 輪播）",
        ["set.tray.rotate"] = "輪播間隔（秒）",
        ["set.tray.style"] = "樣式",
        ["set.tray.style.text"] = "彩色文字",
        ["set.tray.style.badge"] = "彩色底、白色文字",
        ["set.tray.show_unit"] = "顯示單位",
        ["set.tray.bold"] = "粗體",
        ["set.tray.color_override"] = "固定顏色（取代門檻顏色）",
        ["set.tray.pick_color"] = "選擇…",
        ["set.tray.threshold_colors"] = "使用門檻顏色",

        // Settings — sensors
        ["set.sens.col.hardware"] = "硬體",
        ["set.sens.col.sensor"] = "感測器",
        ["set.sens.col.rename"] = "自訂名稱",
        ["set.sens.col.hidden"] = "隱藏",
        ["set.sens.col.yellow"] = "黃色 ≥",
        ["set.sens.col.red"] = "紅色 ≥",
        ["set.sens.suggest"] = "建議門檻",
        ["set.sens.hint"] = "名稱留空表示使用原始名稱。門檻單位與感測器相同（°C、RPM、%）。",

        // Settings — alerts
        ["set.alert.enable"] = "警示",
        ["set.alert.sustain"] = "持續（秒）",
        ["set.alert.sound"] = "音效",
        ["set.alert.sound.system"] = "系統音效",
        ["set.alert.sound.custom"] = "自訂 WAV…",
        ["set.alert.test"] = "測試",
        ["set.alert.hint"] = "數值須持續超過紅色門檻達「持續」秒數才會跳出通知（過濾瞬間尖峰）；數值降回黃色以下後才會再次警示。",

        // Settings — profiles
        ["set.prof.active"] = "使用中設定檔",
        ["set.prof.add"] = "新增",
        ["set.prof.clone"] = "複製",
        ["set.prof.rename"] = "重新命名",
        ["set.prof.delete"] = "刪除",
        ["set.prof.name_prompt"] = "設定檔名稱：",
        ["set.prof.delete_confirm"] = "確定刪除設定檔「{0}」？",
        ["set.prof.hint"] = "每個設定檔有自己的系統匣圖示與門檻覆寫（例如：日常／遊戲／安靜）。",

        // Settings — diagnostics
        ["set.diag.hint"] = "即時顯示輪詢健康狀態與支援資訊；此頁每秒更新一次，不會變更設定。",
        ["set.diag.copy"] = "複製診斷資訊",
        ["set.diag.status"] = "服務狀態",
        ["set.diag.running"] = "執行中",
        ["set.diag.stopped"] = "已停止",
        ["set.diag.successful_polls"] = "成功輪詢次數",
        ["set.diag.failed_polls"] = "失敗輪詢次數",
        ["set.diag.node_failures"] = "硬體節點更新失敗次數",
        ["set.diag.last_poll"] = "最近輪詢耗時",
        ["set.diag.last_snapshot"] = "最近快照讀值數",
        ["set.diag.descriptors"] = "已偵測描述項目",
        ["set.diag.last_success"] = "最近成功輪詢",
        ["set.diag.last_failure"] = "最近失敗時間",
        ["set.diag.failure_detail"] = "失敗詳細資訊",
        ["set.diag.elevation"] = "系統管理員權限",
        ["set.diag.cpu_telemetry"] = "CPU 遙測",
        ["set.diag.pawnio"] = "PawnIO",
        ["set.diag.available"] = "可用",
        ["set.diag.unavailable"] = "不可用",
        ["set.diag.never"] = "尚未發生",
        ["set.diag.none"] = "無",
        ["set.diag.milliseconds"] = "毫秒",
        ["set.diag.history_size"] = "工作階段歷史暫存",
        ["set.diag.history_truncated"] = "（已達上限——最新的取樣不會出現在匯出中）",
        ["set.diag.open_log"] = "開啟診斷記錄",
        ["set.diag.no_log"] = "尚未寫入任何診斷記錄。",
        ["set.diag.ec_explorer"] = "EC 暫存器探索器…",

        // Settings tooltips
        ["tip.tabs"] = "選擇設定類別；將滑鼠停在個別選項上可查看詳細說明。",
        ["tip.tab.general"] = "語言、外觀、輪詢、啟動、記錄與監控行為。",
        ["tip.tab.tray"] = "設定通知區域圖示，以及每個圖示顯示的感測器讀值。",
        ["tip.tab.sensors"] = "重新命名、隱藏感測器，並設定顯示用的警告門檻。",
        ["tip.tab.alerts"] = "選擇哪些感測器發送通知，以及警示的觸發方式。",
        ["tip.tab.profiles"] = "建立具備獨立系統匣圖示與門檻覆寫的命名設定檔。",
        ["tip.tab.diagnostics"] = "查看即時感測器輪詢健康狀態，並可複製資訊以利排除問題。",
        ["tip.diagnostics.hint"] = "顯示最近輪詢結果、失敗、後端可用性與耗時；此處不會變更任何設定。",
        ["tip.diagnostics.copy"] = "將目前診斷報告複製到剪貼簿，方便附在支援請求或問題回報中。",
        ["tip.diagnostics.open_log"] = "開啟輪替式診斷記錄。與此頁面不同，它會跨越睡眠、當機與重新啟動保留下來，是查明「已經發生過」的問題的地方。",
        ["tip.diagnostics.ec_explorer"] = "開啟嵌入式控制器暫存器探索器，用於在沒有內建對應表的筆電機型上找出風扇暫存器。",
        ["tip.common.apply"] = "儲存目前變更並保持「設定」視窗開啟。",
        ["tip.common.cancel"] = "放棄自上次套用後或開啟此視窗後所做的變更。",
        ["tip.common.ok"] = "儲存變更並關閉「設定」視窗。",

        ["tip.general.language"] = "變更介面語言；按下套用後，「自動」會依 Windows 顯示語言決定。",
        ["tip.general.theme"] = "選擇淺色、深色或自動外觀；自動會依 Windows 應用程式主題決定。",
        ["tip.general.units"] = "僅影響溫度的顯示單位；感測器資料仍以攝氏儲存。",
        ["tip.general.poll_interval"] = "硬體讀取頻率。較短的間隔反應更快，但會增加 CPU 與電池用量。",
        ["tip.general.battery_adaptive"] = "使用電池時會盡可能降低感測工作量以延長續航；讀值更新可能較慢。",
        ["tip.general.autostart"] = "登入時啟動 WinMonitor。系統管理員安裝使用工作排程器；免安裝或一般權限使用 HKCU Run。",
        ["tip.general.autostart_delay"] = "登入後等待一段時間才啟動；適合 Windows 與硬體驅動仍在載入時使用。",
        ["tip.general.start_minimized"] = "啟動時不顯示主視窗，仍可從通知區域圖示使用 WinMonitor。",
        ["tip.general.close_to_tray"] = "使視窗的關閉按鈕改為隱藏 WinMonitor，而不是停止感測器監控。",
        ["tip.general.confirm_on_close"] = "啟用縮小到系統匣時，關閉視窗會先詢問要隱藏還是結束程式。",
        ["tip.general.hotkey"] = "WinMonitor 執行時，可用 Ctrl+Alt+M 切換迷你視窗。",
        ["tip.general.show_cores"] = "在主感測器清單中加入每個 CPU 核心的獨立溫度。關閉時仍會保留封裝或彙總 CPU 溫度。",
        ["tip.general.flag_static"] = "標示不會變動的 ACPI 或其他溫度區，避免被誤認為即時讀值。",
        ["tip.general.throttle"] = "硬體後端支援時，顯示 CPU 過熱降頻狀態感測器。",
        ["tip.general.throttle_toast"] = "開始熱降頻時顯示通知；只有啟用降頻偵測時可用。",
        ["tip.general.auto_reset_daily"] = "每天在選定時間重設本次工作階段的最低、最高與平均值。",
        ["tip.general.auto_reset_time"] = "自動每日重設使用的本機時間。",
        ["tip.general.reset_on_resume"] = "Windows 從睡眠喚醒後清除本次峰值，避免睡眠前後讀值無法比較。",
        ["tip.general.ec_throttle"] = "每 N 次一般輪詢才讀取一次已設定的 EC 感測器。數值越大，EC 存取越少但風扇讀值更新越慢。",
        ["tip.general.logging"] = "將快照寫入每日 CSV 記錄檔；會產生背景磁碟存取。",
        ["tip.general.logging_interval"] = "CSV 每列之間的秒數；此設定與即時輪詢間隔無關。",
        ["tip.general.logging_retention"] = "超過此天數的 CSV 記錄檔會被刪除。",
        ["tip.general.pawnio"] = "顯示選用的已簽章 PawnIO 存取是否可用；它可改善 Windows 上的硬體資料可用性。",
        ["tip.general.restore_defaults"] = "確認後以預設值取代所有設定、設定檔與感測器自訂。",

        ["tip.tray.list"] = "每一列代表一個獨立通知區域圖示；越前面的列會顯示在通知區域越左側。",
        ["tip.tray.add"] = "新增一個空白系統匣圖示項目，接著在右側選擇要顯示的感測器。",
        ["tip.tray.remove"] = "刪除選取的系統匣圖示項目；至少會保留一個項目。",
        ["tip.tray.up"] = "將選取圖示往通知區域左側移動一個位置。",
        ["tip.tray.down"] = "將選取圖示往通知區域右側移動一個位置。",
        ["tip.tray.split"] = "把輪播項目拆成每個已選感測器各一個圖示，並保留其樣式設定。",
        ["tip.tray.sensors"] = "選擇此圖示顯示的讀值。一個讀值會固定顯示；兩個以上會輪播。",
        ["tip.tray.rotate"] = "輪播項目在切換下一個感測器前的顯示秒數；只影響有兩個以上感測器的項目。",
        ["tip.tray.style"] = "選擇選取系統匣圖示使用彩色文字，或使用彩色底的白色文字。",
        ["tip.tray.show_unit"] = "在圖示文字加入 °C、W 或 % 等單位；可供數字使用的空間會變少。",
        ["tip.tray.bold"] = "以粗體繪製系統匣圖示文字，較易辨識但數字可用空間會變少。",
        ["tip.tray.sparkline"] = "在空間與感測器歷史資料足夠時，繪製迷你近期趨勢圖。",
        ["tip.tray.threshold_colors"] = "依感測器綠、黃、紅門檻狀態為圖示文字著色。",
        ["tip.tray.fixed_color"] = "使用選取的固定顏色，並忽略依嚴重程度變色的門檻顏色。",
        ["tip.tray.pick_color"] = "開啟固定顏色的選色器；選擇顏色後會啟用固定顏色模式。",

        ["tip.sens.filter"] = "只顯示硬體名稱或感測器名稱包含輸入文字的資料列。",
        ["tip.sens.grid"] = "編輯每個感測器的名稱、可見性與顯示門檻；停在欄位上可查看該欄的作用。",
        ["tip.sens.hardware"] = "提供此讀值的實體裝置，無法在此處編輯。",
        ["tip.sens.sensor"] = "硬體後端回報的原始感測器名稱，無法在此處編輯。",
        ["tip.sens.rename"] = "可選的替代名稱，會顯示在 WinMonitor 各處；清空即可改回原始硬體名稱。",
        ["tip.sens.hidden"] = "從主清單與所有系統匣項目移除此感測器；不會停止背景硬體輪詢。",
        ["tip.sens.yellow"] = "感測器本身單位的警告色門檻；清空儲存格會繼承全域設定或建議值。",
        ["tip.sens.red"] = "感測器本身單位的嚴重色門檻；清空儲存格會繼承全域設定或建議值。",
        ["tip.sens.suggest"] = "為選取資料列寫入建議的黃／紅門檻，並保留警示設定。",
        ["tip.sens.restore_all"] = "將所有設定檔的黃／紅門檻重設為建議值，同時保留名稱、隱藏旗標與警示。",

        ["tip.alert.filter"] = "只顯示硬體名稱或感測器名稱包含輸入文字的資料列。",
        ["tip.alert.grid"] = "為支援的感測器啟用通知、選擇觸發前的持續時間，以及是否播放音效。",
        ["tip.alert.sensor"] = "受監控的感測器；只有溫度、風扇轉速與功率讀值可以觸發警示。",
        ["tip.alert.enable"] = "數值連續超過紅色門檻達指定時間後啟用通知。",
        ["tip.alert.sustain"] = "超過紅色門檻後、警示觸發前所需的連續秒數；可用範圍為 1 至 3600。",
        ["tip.alert.sound"] = "讓此感測器的警示播放已設定的系統音效或自訂 WAV 檔。",
        ["tip.alert.sound_mode"] = "選擇系統警示音或自訂 WAV 檔，供測試及套用到目前設定檔的所有已啟用警示使用。",
        ["tip.alert.sound_path"] = "自訂 WAV 檔的路徑；只有按下「將音效套用到所有警示」才會儲存。",
        ["tip.alert.browse"] = "選擇要用於警示播放的 WAV 檔。",
        ["tip.alert.test"] = "不儲存變更，直接播放目前選取的系統音效或自訂音效。",
        ["tip.alert.apply_sound_all"] = "將目前音效選擇儲存到目前設定檔的所有已啟用警示，即使清單已篩選也會套用。",

        ["tip.profiles.active"] = "按下套用後，選擇其系統匣圖示與門檻覆寫會生效的設定檔。",
        ["tip.profiles.list"] = "選取要複製、重新命名或刪除的設定檔。每個設定檔各自保存系統匣圖示與門檻設定。",
        ["tip.profiles.new"] = "建立一個具有預設系統匣與門檻設定的新設定檔。",
        ["tip.profiles.clone"] = "把選取設定檔的系統匣圖示與門檻覆寫複製到新的設定檔。",
        ["tip.profiles.rename"] = "只變更選取設定檔的名稱，不會改變其設定內容。",
        ["tip.profiles.delete"] = "確認後刪除選取設定檔；最後保留的一個設定檔無法刪除。",
        ["tip.profiles.name"] = "輸入非空白且不與既有設定檔重複的名稱。",

        // Language-neutral, but present in both dictionaries so the coverage audit stays clean.
        ["set.alert.browse"] = "…",

        // Battery extra
        ["bat.charge"] = "電量",
        ["bat.health"] = "健康度",
        ["bat.rate"] = "功率",
        ["bat.remaining_capacity"] = "剩餘容量",

        // Storage extra
        ["ssd.health"] = "健康度",
        ["ssd.written"] = "已寫入",

        // Common
        ["common.ok"] = "確定",
        ["common.cancel"] = "取消",
        ["common.yes"] = "是",
        ["common.no"] = "否",
        ["common.close"] = "關閉",
        ["common.celsius"] = "攝氏（°C）",
        ["common.fahrenheit"] = "華氏（°F）",
        ["common.none"] = "（無）",
        ["common.error"] = "錯誤",
        ["common.apply"] = "套用",

        // Module-contributed keys
        ["sensor.acpi_zone"] = "ACPI 溫度區域",
        ["startup.register_failed"] = "開機自動啟動註冊失敗：{0}",
        ["startup.task_description"] = "登入 Windows 時自動啟動 WinMonitor。",
        ["main.use_fahrenheit"] = "華氏（°F）",
        ["main.show_chart"] = "顯示圖表",
        ["main.about_text"] = "Windows 輕量硬體監控工具。\n\nCopyright (c) 2026 Michael Lin。\nWinMonitor 自有原始碼採用 MIT License；第三方授權全文隨應用程式提供。\n\n感測器資料由 LibreHardwareMonitor 提供（LibreHardwareMonitorLib，MPL-2.0 授權）。\nhttps://github.com/LibreHardwareMonitor/LibreHardwareMonitor",
        ["main.status.elevated"] = "系統管理員",
        ["main.status.not_elevated"] = "一般權限",
        ["main.status.cpu_unavailable"] = "CPU 遙測無法使用",
        ["main.status.pawnio"] = "已偵測到 PawnIO",
        ["file.csv_filter"] = "CSV 檔案 (*.csv)|*.csv|所有檔案 (*.*)|*.*",
        ["set.tray.icon_label"] = "圖示 {0}：{1}",
        ["set.tray.auto"] = "（自動）",
        ["set.alert.apply_sound_all"] = "將音效套用到所有警示",
        ["set.tray.split"] = "每個感測器一個獨立圖示",
        ["set.tray.independent_hint"] = "左側清單的每一列都是一個獨立的系統匣圖示；只有在同一列勾選多個感測器時，該圖示才會輪播。",
        ["set.sens.restore_all"] = "全部回復建議門檻",
        ["set.sens.restore_all.confirm"] = "將所有感測器（含所有設定檔）的黃/紅門檻回復為建議值？重新命名、隱藏與警示設定會保留。",

        // Embedded Controller (LG 風扇讀取)
        ["ec.title"] = "嵌入式控制器 (EC) 探索器",
        ["ec.hint"] = "三種免猜測找出風扇暫存器的方法。相關性（右上）：正常使用筆電約 1 分鐘，會隨 CPU 溫度／負載變動的暫存器將排在最前，雙擊即可新增。搜尋數值：輸入其他工具顯示的轉速，找出存放它的暫存器。擷取 A／B：先擷取閒置狀態再擷取高負載狀態，只看變化最大的暫存器。",
        ["ec.correlation"] = "可能的風扇／溫度暫存器",
        ["ec.likely_header"] = "依各暫存器與 CPU 溫度／負載的相關程度排序。雙擊即可新增。",
        ["ec.collecting"] = "正在收集樣本… {0}/{1}",
        ["ec.no_candidates"] = "尚無明顯候選項目——請繼續使用筆電。",
        ["ec.target_temp"] = "溫度",
        ["ec.target_load"] = "負載",
        ["ec.find_value"] = "搜尋數值（其他工具顯示的轉速）",
        ["ec.compare"] = "閒置 → 負載差異（變化最大者）",
        ["ec.compare_hint"] = "閒置時按「擷取 A」，高負載時按「擷取 B」。",
        ["ec.compare_none"] = "A 與 B 之間沒有暫存器變化達 3 以上。",
        ["ec.capture_a"] = "擷取 A（閒置）",
        ["ec.capture_b"] = "擷取 B（負載）",
        ["ec.capture_a_done"] = "已擷取 A ✓",
        ["ec.capture_b_done"] = "已擷取 B ✓",
        ["ec.defined"] = "已監控的 EC 感測器",
        ["ec.add"] = "將選取項目新增為感測器…",
        ["ec.remove"] = "移除",
        ["ec.reset_minmax"] = "重設最小/最大值",
        ["ec.select_prompt"] = "選取一個暫存器以查看詳細資訊。",
        ["ec.unavailable"] = "EC 無法使用。請以系統管理員身分執行並確認已安裝 PawnIO。",
        ["ec.likely_fan"] = "此暫存器變動幅度大——可能是風扇／溫度相關暫存器。",
        ["ec.add_title"] = "新增 EC 感測器（暫存器 {0}）",
        ["ec.default_name"] = "CPU 風扇",
        ["ec.field_name"] = "名稱",
        ["ec.field_kind"] = "解讀方式",
        ["ec.field_quantity"] = "數值類型",
        ["ec.field_scale"] = "倍率 (×)",
        ["ec.field_divisor"] = "除數",
        ["ec.big_endian"] = "大端序 16 位元（高位元組在前）",
        ["ec.preview"] = "預覽",
        ["ec.status.available"] = "EC：可用（PawnIO）",
        ["ec.status.pawnio_missing"] = "EC：未安裝 PawnIO",
        ["ec.status.not_elevated"] = "EC：需要系統管理員權限",
        ["ec.status.module_missing"] = "EC：缺少模組檔案",
        ["ec.status.failed"] = "EC：初始化失敗",
        ["ec.enable"] = "啟用嵌入式控制器監控（LG 風扇支援）",

        // Round-3 optimizations
        ["main.show_cores"] = "顯示每核心溫度",
        ["main.fixed_value"] = "(固定值)",
        ["set.battery_adaptive"] = "使用電池時降低輪詢頻率",
        ["set.show_cores"] = "顯示每個 CPU 核心溫度",
        ["set.flag_static"] = "將數值不變的溫度區標記為（固定）",
        ["set.ec_throttle"] = "每 N 次輪詢讀取一次 EC",
        ["set.tray.sparkline"] = "顯示迷你趨勢圖",

        // Round-4 batch
        ["throttle.sensor"] = "CPU 降頻狀態",
        ["throttle.normal"] = "正常",
        ["throttle.active"] = "降頻中",
        ["boolean.true"] = "True",
        ["boolean.false"] = "False",
        ["chart.boolean"] = "狀態",
        ["throttle.toast_title"] = "CPU 降頻中",
        ["throttle.toast_body"] = "CPU 已達溫度上限，正在降低時脈。",
        ["main.ctx.tray"] = "在系統匣顯示",
        ["main.ctx.pin"] = "釘選到最愛",
        ["main.ctx.hide"] = "隱藏此感測器",
        ["main.group.favorites"] = "最愛",
        ["main.rescan"] = "重新掃描硬體",
        ["main.statuscard.copy"] = "複製狀態卡圖片",
        ["main.statuscard.save"] = "儲存狀態卡圖片…",
        ["set.filter"] = "篩選感測器…",
        ["set.theme"] = "外觀主題",
        ["set.theme.auto"] = "自動",
        ["set.theme.light"] = "淺色",
        ["set.theme.dark"] = "深色",
        ["set.hotkey"] = "全域快速鍵切換迷你視窗（Ctrl+Alt+M）",
        ["set.throttle"] = "偵測 CPU 降頻",
        ["set.throttle_toast"] = "開始降頻時通知",
        ["set.autoreset_daily"] = "每天定時重設峰值",
        ["set.autoreset_resume"] = "喚醒時重設峰值",
    };
}
